### ISSUE TITLE
Installation guides for Linux (Ubuntu and Fedora)

### ISSUE THREAD

**Issue by Ahmed-A-Dev** [SamSike/OpenDrop_OP#34]

**Comment by Ahmed-A-Dev** [comment]
Both the installation script and guide are done for Fedora. They can be accessed [here](https://unimelbcloud.sharepoint.com/:t:/r/teams/OpenDropOP/Shared%20Documents/General/Dev%20Environment%20Setup/[FedoraInstallationGuide.md](https://unimelbcloud.sharepoint.com/:t:/r/teams/OpenDropOP/Shared%20Documents/General/Dev%20Environment%20Setup/FedoraInstallationGuide.md?csf=1&web=1&e=acEd9Y)?csf=1&web=1&e=acEd9Y)

**Comment by aoxiangx** [comment]
Both the installation script and guide are done for Ubuntu.
