### ISSUE TITLE
Structure analysis - output data location(opendrop)

### ISSUE THREAD

**Issue by lvqq2000** [SamSike/OpenDrop_OP#42]
Output data location feature:
- Analyze how OpenDrop and Conan-ML implement this feature.
- Identify the differences between the output data location features of OpenDrop and Conan-ML.
- Determine how to integrate the output data location features of both applications.
- Try integrating this feature
- Assess the code structure, maintainability, and readability with regard to the corresponding feature.

Write your findings in the shared file on Teams (General->Intergration->Structure Analysis)

**Comment by aoxiangx** [comment]
great job !
