### ISSUE TITLE
Setup a Docker for OpenDrop

### ISSUE THREAD

**Issue by SamSike** [SamSike/OpenDrop_OP#5]
Goal: OpenDrop works in Linux PC (using docker)

11:25PM 21/08/2024 Ahmed: a clean Fedora 35 Docker image with all the dependencies required for OpenDrop. FedoraOD.zip file has been uploaded to Teams, make sure to read the README file.

**Comment by lvqq2000** [comment]
This issue is no longer appliable since the team has pivoted and decided to change to use Conan-ml as the base instead of OpenDrop
