### ISSUE TITLE
Overall structure analysis for integration

### ISSUE THREAD

**Issue by lvqq2000** [SamSike/OpenDrop_OP#58]

**Comment by aoxiangx** [comment]
1.`Opendrop already supports a navigation system that allows users to switch between different experiment types. conan-ml's functionalities can be incorporated into this existing system as an additional experiment type (alongside the existing IFT and CONAN experiments).`
We are not going to have a 3rd experiment type alongside with the current 2, the plan is replace the current CONAN with the advanced CONAN-ML. So the wording might need to be changed.

Refer to the attachment, `Maintaining the Modularity` need to be more specific. For instance, the Opendrop is kinda modular in UI wise, meanwhile its code base is not very modular (at least for me). As client would like to have the Code-wise modularity, we can constrain this part to `Maintaining the UI-wise Modularity only.` (Or any other better description)

**Comment by Ahmed-A-Dev** [comment]
@aoxiangx and I have discussed this further and found it useful to add Conan-ML as a 3rd experiment for now and then remove the original OpenDrop experiment at the end of development.

will consider this reviewed and close it.
