### ISSUE TITLE
README.md for the application

### ISSUE THREAD

**Issue by lvqq2000** [SamSike/OpenDrop_OP#66]
Update the readme file (should be stored in the Teams file for now):

- Add a more detailed description of the application.
- Include a software specification section to outline the code structure (leave this blank for now, as we will modify the code).
- Add a user manual section for installation.
- Consider adding other sections as needed (refer to README files from other projects for inspiration).

**Comment by MnnDa** [comment]
added :  background, OpenDrop-ML Software Specification, part.
checked: user guide, part
