### ISSUE TITLE
Sprint 4 planning meeting note

### ISSUE THREAD

**Issue by lvqq2000** [SamSike/OpenDrop_OP#88]

**Comment by Ahmed-A-Dev** [comment]
@lvqq2000 Hi this has been completed and uploaded to the teams [here](https://unimelbcloud.sharepoint.com/:w:/r/teams/OpenDropOP/Shared%20Documents/General/Docs/Communication/Agile%20Ceremonies/Sprint%204/Sprint%204%20Planning%20Meeting.docx?d=wb8d2a55ed7e54c68a57fbda20ebebe99&csf=1&web=1&e=1G9IIp) please review it, and close this task if you do not have any proposed changes.

**Comment by lvqq2000** [comment]
It looks great! My only suggestion would be to make the sprint goals more specific. They should be measurable (allow us to determine whether they have been completed by the end of the sprint).

**Comment by Ahmed-A-Dev** [comment]
@lvqq2000 I made the changes you requested, please have a look again.
