### ISSUE TITLE
Structure analysis - analysis methods (OpenDrop)

### ISSUE THREAD

**Issue by lvqq2000** [SamSike/OpenDrop_OP#91]
Analysis methods feature:

- Analyze how OpenDrop implements this feature.
- Determine how to integrate the analysis methods features.
- Assess the code structure, maintainability, and readability with regard to the corresponding feature.

Write your findings in the shared file on Teams (General->Docs->Architecture and Design->Structure Analysis)

**Comment by aoxiangx** [comment]
Done, the updated file can be checked at [Analysis Methods](https://unimelbcloud.sharepoint.com/:w:/r/teams/OpenDropOP/Shared%20Documents/General/Docs/Architecture%20and%20Design/Structure%20Analysis/Analysis%20Methods/[OpenDrop.docx](https://unimelbcloud.sharepoint.com/:w:/r/teams/OpenDropOP/Shared%20Documents/General/Docs/Architecture%20and%20Design/Structure%20Analysis/Analysis%20Methods/OpenDrop.docx?d=w0722dfd0b18648d58f534143a3364862&csf=1&web=1&e=EMADZt)?d=w0722dfd0b18648d58f534143a3364862&csf=1&web=1&e=EMADZt)
