### ISSUE TITLE
Update integration plan according to the dicussion

### ISSUE THREAD

**Issue by aoxiangx** [SamSike/OpenDrop_OP#96]
Look into relevant docs and make the changes

**Comment by Ahmed-A-Dev** [comment]
both integration analysis and plan are completed and can be found [here](https://unimelbcloud.sharepoint.com/:t:/r/teams/OpenDropOP/Shared%20Documents/General/Docs/Architecture%20and%20Design/Integration%20Analysis%20V2.md?csf=1&web=1&e=Gi30nY) Please review it @aoxiangx.

**Comment by aoxiangx** [comment]
All good with integration analysis.
However, one point in plan that I would like to talk.
1.  For UAT, the client is currently our only user. Our strategy is to have them go through the entire process independently, without providing any guidance. Any observed obstacles or difficulties they encounter will indicate areas where our system design is lacking. This feedback will be sufficient for us to make improvements at this stage, so there's no need to deploy a test instance or gather broader user feedback for now.

**Comment by Ahmed-A-Dev** [comment]
@aoxiangx I have made changes to the integration plan to match your feedback, please have a look.
