### ISSUE TITLE
Update integration diagram

### ISSUE THREAD

**Issue by aoxiangx** [SamSike/OpenDrop_OP#97]
Update the diagram following the new integration plan

**Comment by aoxiangx** [comment]
The updated diagram can be viewed via the link. @lvqq2000 Please review it.

[High-Level Project Diagram_v2](https://unimelbcloud.sharepoint.com/:b:/r/teams/OpenDropOP/Shared%20Documents/General/Docs/Project%20Plan/High-Level%20Project%20Diagram_v2.pdf?csf=1&web=1&e=KRFdI1)

**Comment by lvqq2000** [comment]
it might be better to specify that the two branches of OpenDrop2 represent 2 key functionalities of OpenDrop2. I was a bit confused by it when I saw this since these 2 branches look similar.

**Comment by aoxiangx** [comment]
@lvqq2000 I've updated and uploaded the diagram according to instructions. Please check.
[High-Level Project Diagram_v2](https://unimelbcloud.sharepoint.com/:b:/r/teams/OpenDropOP/Shared%20Documents/General/Docs/Project%20Plan/High-Level%20Project%20Diagram_v2.pdf?csf=1&web=1&e=GJzCHa)
